# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 02:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateField(default=datetime.datetime(2016, 4, 25, 2, 39, 14, 668191, tzinfo=utc))),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('descripcion', models.TextField(help_text=b'Introduzca una breve rese\xc3\xb1a del proyecto', max_length=140, null=True)),
                ('estado', models.CharField(choices=[(b'PEN', b'Pendiente'), (b'ANU', b'Anulado'), (b'ACT', b'Activo'), (b'FIN', b'Finalizado')], default=b'PEN', help_text=b'Estado del proyecto', max_length=3)),
                ('observaciones', models.TextField(default=b'No hay observaciones', max_length=140, null=True)),
                ('lider_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lider', to='login.Usuario')),
            ],
        ),
    ]
