# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 02:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20160427_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.Cliente'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaCreacion',
            field=models.DateField(default=datetime.datetime(2016, 4, 27, 2, 6, 14, 43955, tzinfo=utc)),
        ),
    ]
