# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 16:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20160427_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='fechaFin',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='fechaInicio',
            new_name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fechaCreacion',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2016, 4, 27, 16, 50, 24, 909235, tzinfo=utc)),
        ),
    ]
