# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0012_auto_20160427_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(help_text='Introduzca una breve rese\xf1a del proyecto', max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2016, 5, 1, 20, 59, 28, 408403, tzinfo=utc)),
        ),
    ]
