# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='')),
                ('duracion', models.IntegerField(default=0)),
                ('estado_sprint', models.CharField(choices=[('PEN', 'Pendiente'), ('INI', 'Iniciado'), ('FIN', 'Finalizado')], default='PEN', max_length=3)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(null=True)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='proyecto.Proyecto')),
            ],
            options={
                'permissions': (('ver_sprint', 'Puede ver Sprint'), ('crear_sprint', 'Puede crear un nuevo Sprint'), ('borrar_sprint', 'Puede eliminar un sprint')),
            },
        ),
    ]
