# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20160514_1929'),
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'permissions': (('ver_sprint', 'Puede ver Sprint'), ('crear_sprint', 'Puede crear un nuevo Sprint'))},
        ),
        migrations.AddField(
            model_name='sprint',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto'),
        ),
    ]
