# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'permissions': (('view_sprint', 'Puede ver Sprint'), ('asignar_us', 'Puede asignar US al Sprint'), ('iniciar_sprint', 'Puede iniciar el Sprint'))},
        ),
    ]
