# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_auto_20160515_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='proyecto.Proyecto'),
        ),
    ]
