# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 13:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0003_auto_20160515_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'permissions': (('ver_sprint', 'Puede ver Sprint'), ('crear_sprint', 'Puede crear un nuevo Sprint'), ('borrar_sprint', 'Puede eliminar un sprint'))},
        ),
        migrations.AddField(
            model_name='sprint',
            name='estado_sprint',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('INI', 'Iniciado'), ('FIN', 'Finalizado')], default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='sprint',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2016, 5, 28, 13, 12, 1, 694468, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
