# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('proyecto', '0013_auto_20160501_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
            ],
            bases=('auth.group',),
        ),
    ]
