# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_auto_20160502_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='proyecto.Proyecto'),
        ),
    ]
