# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='formato_notificaciones',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='hora_notificaciones',
        ),
    ]
