# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Notificacion de equipos creados',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Notificacion de proyectos creados',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Notificacion de usuarios creados',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='hora_notificaciones',
            field=models.TimeField(null=True),
        ),
    ]
