# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20160502_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='formato_notificaciones',
            field=models.CharField(choices=[('htm', 'HTML'), ('txt', 'Texto Plano')], default='htm', help_text='Formato', max_length=3),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='cliente.Cliente'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='login.Usuario'),
        ),
    ]
