# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20160502_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Notificacion de equipos creados',
            new_name='noti_creacion_equipos',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Notificacion de proyectos creados',
            new_name='noti_creacion_proyecto',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Notificacion de usuarios creados',
            new_name='noti_creacion_usuario',
        ),
    ]
