# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20160502_0332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': (('can_view', 'Puede ver cliente'),)},
        ),
    ]
