# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='US',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_corta', models.TextField(default='')),
                ('descripcion_larga', models.TextField(default='')),
                ('tiempo_planificado', models.IntegerField(default=0)),
                ('valor_negocio', models.IntegerField(default=0)),
                ('urgencia', models.IntegerField(default=0)),
                ('tipoUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='US.TipoUS')),
            ],
        ),
        migrations.AddField(
            model_name='actividades',
            name='tipoUS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='US.TipoUS'),
        ),
    ]
