# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='')),
                ('numero', models.IntegerField(default=0)),
            ],
            options={
                'permissions': (('ver_actividades', 'Puede ver actividades'), ('crear_actividades', 'Puede crear actividades')),
            },
        ),
        migrations.CreateModel(
            name='TipoUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='')),
            ],
            options={
                'permissions': (('ver_tipo_US', 'Puede ver tipos de US'),),
            },
        ),
        migrations.CreateModel(
            name='US',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_corta', models.TextField(default='')),
                ('descripcion_larga', models.TextField(default='')),
                ('tiempo_planificado', models.IntegerField(default=0)),
                ('valor_negocio', models.IntegerField(default=1)),
                ('urgencia', models.IntegerField(default=1)),
                ('finalizado', models.BooleanField(default=False)),
                ('estado_actividad', models.CharField(choices=[('TOD', 'Todo'), ('DOI', 'Doing'), ('DON', 'Done')], default='TOD', max_length=3)),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='US.Actividades')),
            ],
            options={
                'permissions': (('ver_US', 'Puede ver US'), ('crear_US', 'Puede crear US'), ('change_actividad', 'Puede cambiar actividad'), ('change_estado_actividad', 'Puede cambiar el estado de actividad'), ('repriorizar', 'Puede repriorizar el US')),
            },
        ),
    ]
