# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sprint', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0002_auto_20160615_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='')),
                ('numero', models.IntegerField(default=0)),
            ],
            options={
                'permissions': (('ver_actividades', 'Puede ver actividades'), ('crear_actividades', 'Puede crear actividades')),
            },
        ),
        migrations.CreateModel(
            name='TipoUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='')),
            ],
            options={
                'permissions': (('ver_tipo_US', 'Puede ver tipos de US'),),
            },
        ),
        migrations.CreateModel(
            name='US',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_corta', models.TextField(default='')),
                ('descripcion_larga', models.TextField(default='')),
                ('tiempo_planificado', models.IntegerField(default=0)),
                ('valor_negocio', models.IntegerField(default=1)),
                ('urgencia', models.IntegerField(default=1)),
                ('finalizado', models.BooleanField(default=False)),
                ('estado_actividad', models.CharField(choices=[('TOD', 'Todo'), ('DOI', 'Doing'), ('DON', 'Done')], default='TOD', max_length=3)),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='US.Actividades')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uss', to='proyecto.Proyecto')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uss', to='sprint.Sprint')),
                ('tipoUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uss', to='US.TipoUS')),
                ('usuario_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('ver_US', 'Puede ver US'), ('crear_US', 'Puede crear US'), ('change_actividad', 'Puede cambiar actividad'), ('change_estado_actividad', 'Puede cambiar el estado de actividad'), ('repriorizar', 'Puede repriorizar el US')),
            },
        ),
        migrations.AddField(
            model_name='actividades',
            name='tipoUS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='US.TipoUS'),
        ),
    ]
