# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20160514_1929'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprint', '0001_initial'),
        ('US', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividades',
            options={'permissions': (('ver_actividades', 'Puede ver actividades'), ('crear_actividades', 'Puede crear actividades'))},
        ),
        migrations.AlterModelOptions(
            name='tipous',
            options={'permissions': (('ver_tipo_US', 'Puede ver tipos de US'), ('crear_Tipo_US', 'Puede crear Tipos de US'))},
        ),
        migrations.AlterModelOptions(
            name='us',
            options={'permissions': (('ver_US', 'Puede ver US'), ('crear_US', 'Puede crear US'))},
        ),
        migrations.AddField(
            model_name='us',
            name='actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='US.Actividades'),
        ),
        migrations.AddField(
            model_name='us',
            name='estado_actividad',
            field=models.CharField(choices=[('TOD', 'Todo'), ('DOI', 'Doing'), ('DON', 'Done')], default='TOD', max_length=3),
        ),
        migrations.AddField(
            model_name='us',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto'),
        ),
        migrations.AddField(
            model_name='us',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sprint.Sprint'),
        ),
        migrations.AddField(
            model_name='us',
            name='usuario_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
