# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('US', '0002_auto_20160515_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='us',
            options={'permissions': (('ver_US', 'Puede ver US'), ('crear_US', 'Puede crear US'), ('change_actividad', 'Puede cambiar actividad'), ('change_estado_actividad', 'Puede cambiar el estado de actividad'))},
        ),
        migrations.AddField(
            model_name='actividades',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='us',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='tipoUS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='US.TipoUS'),
        ),
        migrations.AlterField(
            model_name='us',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uss', to='proyecto.Proyecto'),
        ),
        migrations.AlterField(
            model_name='us',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uss', to='sprint.Sprint'),
        ),
        migrations.AlterField(
            model_name='us',
            name='tipoUS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uss', to='US.TipoUS'),
        ),
        migrations.AlterField(
            model_name='us',
            name='urgencia',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='us',
            name='valor_negocio',
            field=models.IntegerField(default=1),
        ),
    ]
