# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('US', '0002_auto_20160615_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='us',
            options={'permissions': (('ver_US', 'Puede ver US'), ('change_actividad', 'Puede cambiar actividad'), ('change_estado_actividad', 'Puede cambiar el estado de actividad'), ('repriorizar', 'Puede repriorizar el US'))},
        ),
    ]
